name: cuy_test
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Intl
  intl: ^0.17.0
  intl_utils: ^2.6.0
  equatable: ^2.0.3
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  provider: ^6.0.5
  dio: ^4.0.6
  dartz: ^0.10.1
  modal_progress_hud_nsn: ^0.3.0
  # Environment
  envify: ^2.0.2
  flutter_launcher_icons: ^0.11.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any 
  envify_generator: ^2.0.0
  
  
  

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
  - res/images/

# Language Internazionalization
flutter_intl:
  enabled: true
  class_name: S
  main_locale: es
